[project]
name = "finetuning-instruct-model-for-function-calling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "datasets>=3.6.0",
    "dotenv>=0.9.9",
    "ipywidgets>=8.1.7",
]
